### ISSUE TITLE
Two potential bugs.

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [rhummelmose/BluetoothKit#26]
Thank you for writing this repo which save me a lot of time.  
Here are two potential bug I came across:  
First, `Core Bluetooth` seems to have a slight chance to call `func centralManager(central: CBCentralManager, didConnectPeripheral peripheral: CBPeripheral)` twice for a single connecting behavior.
Code following may output `core bluetooth bug?` when keeping switching on and off bluetooth.

```Swift
internal func centralManager(central: CBCentralManager, didConnectPeripheral peripheral: CBPeripheral) {
        if self.connectionAttempts.count == 0 {
            print("core bluetooth bug?")
        }
        succeedConnectionAttempt(connectionAttemptForPeripheral(peripheral)!)
    }
```

The second one is that if an timeOut error occur . `failConnectionAttempt` will be called, which call `cancelPeripheralConnection` and `cancelPeripheralConnection` lead to call of `didFailToConnectPeripheral `, and when `didFailToConnectPeripheral` happen, the corresponding `connectionAttempt` is already removed and the program will crash .

IMO, both of those two bug can be avoided by avoiding force unwrap result of `connectionAttemptForPeripheral`.

PS: There is a good chance that I mistake something .

**Comment by rhummelmose** [comment]
Hi Nick. Thanks for the report, I will try to reproduce and fix it.

**Comment by rhummelmose** [comment]
It will probably take me a month before I get time to look at this. Please provide a PR if you're able to fix the issue.

**Comment by Nick-The-Uncharted** [comment]
Okay, I will try to find time to do that, I was just not sure whether I mistake something .
