### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by pangpingfei** [rhummelmose/BluetoothKit#28]
internal func centralManager(central: CBCentralManager, didFailToConnectPeripheral peripheral: CBPeripheral, error: NSError?) {
        failConnectionAttempt(connectionAttemptForPeripheral(peripheral)!, error: .Internal(underlyingError: error))
    }

Optional("Optional(TPMS.BKError.InternalError(Optional(TPMS.BKConnectionPool.Error.TimeoutElapsed)))")
fatal error: unexpectedly found nil while unwrapping an Optional value

Occurs when the connection is bad bluetooth.

![qq20160616-0 2x](https://cloud.githubusercontent.com/assets/8135408/16105994/d9159642-33c2-11e6-9dab-c9d2a2686f2e.png)

**Comment by rhummelmose** [comment]
It will probably take me a month before I get time to look at this. Please provide a PR if you're able to fix the issue.
