### ISSUE TITLE
swift3 support

### ISSUE THREAD

**Issue by utopianism** [rhummelmose/BluetoothKit#29]
is it have plan for swift3?

**Comment by rhummelmose** [comment]
Yep. You can create a PR if you need it within a few months :)

**Comment by calebkleveter** [comment]
@utopianism , the version for Swift 3 has been released, but I think you have to get that version through GitHub as it has not been pushed to CocoaPods as far as I know.

    pod 'BluetoothKit', :git => 'https://github.com/rhummelmose/BluetoothKit.git'

**Comment by rhummelmose** [comment]
Correct, I will push it to CocoaPods

**Comment by lou-lan** [comment]
I still have some mistakes in swift3.
<img width="1348" alt="2016-10-04 2 34 18" src="https://cloud.githubusercontent.com/assets/13095837/19048982/16743692-89db-11e6-81bb-19f25f324679.png">

**Comment by HoonAhn** [comment]
When i typed
$ pod install
this error comes up
Analyzing dependencies
[!] The dependency `BluetoothKit (from `https://github.com/rhummelmose/BluetoothKit.git`)` is not used in any concrete target.

what should i do?

**Comment by calebkleveter** [comment]
@HoonAhn , you should open a different issue for this.
