### ISSUE TITLE
Add support for chunking of data. Currently read/writes of data that is too long silently fail

### ISSUE THREAD

**Issue by Daij-Djan** [rhummelmose/BluetoothKit#32]
Add support for chunking of data. Currently read/writes of data that is too long silently fail

**Comment by Daij-Djan** [comment]
e.g. follow https://karp.id.au/a/2015/09/03/reliable-data-transfer-with-ios-bluetooth-le/

Ill look into providing a 'fix' one of these days

**Comment by rhummelmose** [comment]
It already chunks the data. Can you give me an example where it fails?

**Comment by Daij-Djan** [comment]
sorry the problem is different and aaaanyway: I was being dumb and lazy here :)
I didn't get the concept of BKSendDataTask(s)
