### ISSUE TITLE
Question: Can BluetoothKit advertise and scan when the app enters background mode?

### ISSUE THREAD

**Issue by marvelousmishig** [rhummelmose/BluetoothKit#43]

**Comment by rhummelmose** [comment]
Please read the following:
https://developer.apple.com/library/ios/documentation/NetworkingInternetWeb/Conceptual/CoreBluetooth_concepts/CoreBluetoothBackgroundProcessingForIOSApps/PerformingTasksWhileYourAppIsInTheBackground.html

Short answer: Yes, depending on what you put in the info plist and how much power your app consumes compared to the state of resources on the device.
