### ISSUE TITLE
Merging Swift 3

### ISSUE THREAD

**Issue by calebkleveter** [rhummelmose/BluetoothKit#47]
Now that Xcode 8 and Swift 3 have been officially released, should we merge the swift-3 branch into master?

**Comment by rhummelmose** [comment]
Yes. Do you have the access to perform the change, then you are welcome to do so?

**Comment by calebkleveter** [comment]
I cannot perform the merge myself. I would have to submit a PR. https://github.com/rhummelmose/BluetoothKit/pull/48

**Comment by lfarah** [comment]
Would love to have this lib in Swift 3.....
