### ISSUE TITLE
ios10: removed willRestoreState delegate so we get no warning about missing restorationID

### ISSUE THREAD

**Issue by Daij-Djan** [rhummelmose/BluetoothKit#50]
Hi,
for ios10: removed willRestoreState delegate so we get no warning about missing restorationID

//    internal func peripheralManager(peripheral: CBPeripheralManager, willRestoreState dict: [String : AnyObject]) {
//        // print("peripheralManager: \(peripheral) willRestoreState: \(dict)")
//    }

**Comment by erparker** [comment]
Also curious about this. Are there plans to add state restoration into the Swift 3 version?

**Comment by rhummelmose** [comment]
Create a PR

**Comment by mrdavidrees** [comment]
resolved in #54

**Comment by rhummelmose** [comment]
Thanks @mrdavidrees!
