### ISSUE TITLE
Swift3 branch requires iOS 10+ now

### ISSUE THREAD

**Issue by 3ph** [rhummelmose/BluetoothKit#53]
Is there any reason for this?

**Comment by calebkleveter** [comment]
Yes. Apple merged the two classes `CBPeripheralManager` and `CBCentralManager` in to one class, `CBManager`. `CBManager` is only available in iOS 10, so you are going to need that latest iOS SDK to develop with Bluetooth. This means you will need to install Xcode 8.0.

**Comment by 3ph** [comment]
Hi, can you point me to where did you find this? Only changes in API I could find is that CBManager is new superclass of the CBPeripheralManager and CBCentralManager. The state was moved there, nothing else.

Neither of these classes were deprecated. Could find any reason why the drastic change of deployment target was necessary?

Thanks

**Comment by mrdavidrees** [comment]
resolved in #54

**Comment by rhummelmose** [comment]
Thanks @mrdavidrees!
