### ISSUE TITLE
CocoaPods release is not compatible with Swift 3

### ISSUE THREAD

**Issue by Hustenbonbon** [rhummelmose/BluetoothKit#61]
Hey, great work as it seems!

Unfortunately, it seems to me that you integrated Swift 3 support, but you didn't release it to CocoaPods yet, is there a specific reason for that?

Cheers!

**Comment by rhummelmose** [comment]
Because I haven't created a release yet, sorry. Will do it today.

**Comment by indrajitsinh** [comment]
any update ?

**Comment by Appsido** [comment]
Hey, that would be really nice to push swift 3 to cocoapods.

**Comment by michaelom** [comment]
any update on the release?

**Comment by rhummelmose** [comment]
Give me an hour :)

**Comment by rhummelmose** [comment]
Fixed!

**Comment by Appsido** [comment]
👍
