### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by bleeckerj** [rhummelmose/BluetoothKit#65]
For cocoapods, your short useful note on how to specify BluetoothKit in the Podfile specifies version 0.2.0 — I believe it should be 0.4.0.

**Comment by ibrahimuslu** [comment]
Thank you, it helped me .

**Comment by rhummelmose** [comment]
See #ef103b5

**Comment by rhummelmose** [comment]
And thanks @bleeckerj for the heads-up :)

**Comment by adamontherun** [comment]
Readme is still showing 0.2.0

Which had some errors when i tried to build. bumping to 0.4.0 helped
