### ISSUE TITLE
Not able to connect\communicate os x to iOS device.

### ISSUE THREAD

**Issue by BluePick** [rhummelmose/BluetoothKit#71]
Create Mac as Central and iPhone app as peripheral but app can not connect.

**Comment by Mylittleswift** [comment]
@BluePick just using Bluetoothkit or CoreBluetooth cannot pair to each other,  here is the explanation: https://discussions.apple.com/docs/DOC-7722
You need to [Use Continuity to connect your Mac, iPhone, iPad, iPod touch, and Apple Watch](https://support.apple.com/en-us/HT204681)

**Comment by BluePick** [comment]
Thanks for information
