### ISSUE TITLE
ipad 2 Bluetooth Unavailable (Unsupported)

### ISSUE THREAD

**Issue by KanybekMomukeyev** [rhummelmose/BluetoothKit#87]
Hi, thanks for great library!
But why on iPad 2 this library is not working, 
have issue like this: Bluetooth Unavailable (Unsupported)

**Comment by rhummelmose** [comment]
Probably because iPad 2 doesn’t support BLE 😊

 

R.

**Comment by KanybekMomukeyev** [comment]
@rhummelmose thanks for reply, you are correct!
Here more information: https://www.iphonefaq.org/archives/973945

**Comment by danloughney** [comment]
The general rule is that if the device has a Lightning connector then it will work with BLE apps. The exception is the original iPad mini, which really is a shrunken down iPad2.
