### ISSUE TITLE
Hello, I'd like to ask you a question

### ISSUE THREAD

**Issue by Deepblue1996** [rhummelmose/BluetoothKit#92]
I want to achieve ios background bluetooth broadcast data transmission，I looked for information on the Internet，plist File Required background modes item add App communicates using CoreBluetooth and App shares data using CoreBluetooth.I have solved the background program to stop running, but bluetooth is not broadcast out.

**Comment by Diiaablo95** [comment]
Bluetooth ID is not broadcasted during background. As explicitely stated in the [Apple programming guide](https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/CoreBluetooth_concepts/CoreBluetoothBackgroundProcessingForIOSApps/PerformingTasksWhileYourAppIsInTheBackground.html#//apple_ref/doc/uid/TP40013257-CH7-SW1).
